appearance:
  default: system
  switcher: true

theme:
  colorPalettes:
    default:
      light:
        - "#1E3A8A"
        - "#2563EB"
        - "#16A34A"
        - "#F59E0B"
        - "#DC2626"
      dark:
        - "#1E40AF"
        - "#3B82F6"
        - "#22C55E"
        - "#FBBF24"
        - "#EF4444"
  colorScales:
    default:
      light:
        - "#ADD8E6"
        - "#00008B"
      dark:
        - "#ADD8E6"
        - "#00008B"

  colors:
    primary:
      light: "#3b82f6"
      dark: "#60a5fa"
    accent:
      light: "#c2410c"
      dark: "#fdba74"
    base:
      light: "#09090b"
      dark: "#09090b"
    info:
      light: "#0284c7"
      dark: "#38bdf8"
    positive:
      light: "#16a34a"
      dark: "#4ade80"
    warning:
      light: "#f8c900"
      dark: "#fbbf24"
    negative:
      light: "#dc2626"
      dark: "#f87171"

plugins:
  components:
    "@evidence-dev/core-components": {}

  datasources:
    "@evidence-dev/bigquery": {}
    "@evidence-dev/csv": {}
    "@evidence-dev/databricks": {}
    "@evidence-dev/duckdb": {}
    "@evidence-dev/mssql": {}
    "@evidence-dev/mysql": {}
    "@evidence-dev/postgres": {}
    "@evidence-dev/source-javascript": {}
    "@evidence-dev/snowflake": {}
    "@evidence-dev/sqlite": {}
    "@evidence-dev/trino": {}
    "@evidence-dev/motherduck": {}
